### ISSUE TITLE
ImmediateDeprecationError:  Yahoo Actions has been immediately deprecated due to large breaks in the API without the introduction of a stable replacement. 

### ISSUE THREAD

**Issue by david2588e** [pydata/pandas-datareader#487]
Yahoo Finance data looks not working well not 2018/2/14:

ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by bashtage** [comment]
Yahoo changed their API so that the old pandas 0.5 code did not work.  If you would like to fix this, PRs are welcome.

**Comment by stoffprof** [comment]
I am willing to work on this, but want to check if there's a known reason why my approach isn't good.

It looks like a loading a page like this:

[https://finance.yahoo.com/quote/%5EGSPC/history?period1=-630961200&period2=1518498000&interval=1d&filter=history&frequency=1d](https://finance.yahoo.com/quote/%5EGSPC/history?period1=-630961200&period2=1518498000&interval=1d&filter=history&frequency=1d)

has all of the historical price data for the requested ticker stored in JSON format. (Search for "HistoricalPriceStore" in the source.) Can't we just pull that down? No need for a crumb, reading CSVs, etc.

Am I missing something?

**Comment by bashtage** [comment]
Normally PDF has avoided scraping since this seems to be especially fragile.  This said I think that Yahoo was a very important contribution and so if you can reliably scrape the data, then this would be welcome in this instance.

**Comment by sudoFerraz** [comment]
What are you guys using for FOREX currency tickers?
I was using the yahoo data for my system, and now it is all broke since then...
It was the only FREE source of data of FOREX from pdf...

**Comment by stoffprof** [comment]
I've been having trouble implementing this within the existing code. (I'm not an experienced coder.) But the code below works if someone can modify it as needed. Otherwise, I'll keep trying to get a useable PR.

https://gist.github.com/stoffprof/719ae8d876d3a5539112e74d292339c9

**Comment by addisonlynch** [comment]
@sudoFerraz AlphaVantage could be an option for this. Haven't gotten around to writing a PR to implement, but would be a good idea.

See [their docs](https://www.alphavantage.co/documentation/#fx) for more info

**Comment by luferazth** [comment]
I've been coding in python and i want to repair this. What should i do?

**Comment by bashtage** [comment]
@luferazth See #489 which has what looks like a reasonable fix, given the current API available.

**Comment by sudoFerraz** [comment]
Just updated pandas today, and datareader at least from the FOREX ticker I was using is now back to normal!
Thank you @stoffprof , that saved my skin with my client :dancing_men:

**Comment by leong0803** [comment]
Thanks @stoffprof , that works perfectly with stocks.
Is there any other way to get currency data from yahoo please?

**Comment by david2588e** [comment]
Thanks for stoffprof great job !
The Yahoo API issue partly fixed, only forex data has some issues.

**Comment by stoffprof** [comment]
I will try to add Forex data in the next few days.

**Comment by rsvp** [comment]
@stoffprof Nice, thanks!

How are FX symbols constructed at Yahoo, say, e.g. EURJPY 
for the Euro cross-rate against Japanese Yen ?

**Comment by sudoFerraz** [comment]
What happened? It just stopped working again o.o

**Comment by bashtage** [comment]
The perils of scraping.

**Comment by stoffprof** [comment]
What's not working? Still fine for me.

**Comment by stoffprof** [comment]
FX data can be accessed using YahooFXReader with PR #498 
@leong0803
@david2588e

**Comment by sudoFerraz** [comment]
You can reproduce the error querying the ticker 
df = pandas_datareader.DataReader('BRL=X', 'yahoo')

output:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ferraz/anaconda2/lib/python2.7/site-packages/pandas_datareader/data.py", line 291, in DataReader
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Daily'))
pandas_datareader.exceptions.ImmediateDeprecationError:
Yahoo Daily has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

**Comment by bashtage** [comment]
That looks like 0.6.0. What is the version string of the pdr you are using?

**Comment by sudoFerraz** [comment]
> That looks like 0.6.0. What is the version string of the pdr you are using?

Yes it is : 
`>>> pandas_datareader.__version__
u'0.6.0'`

But it is not the last one?
When I try to upgrade : 
`

Requirement already up-to-date: pandas_datareader in /Users/ferraz/anaconda2/lib/python2.7/site-packages
Requirement already up-to-date: requests-ftp in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: requests-file in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: lxml in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: wrapt in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: requests>=2.3.0 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: pandas>=0.19.2 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas_datareader)
Requirement already up-to-date: six in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from requests-file->pandas_datareader)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from requests>=2.3.0->pandas_datareader)
Requirement already up-to-date: idna<2.7,>=2.5 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from requests>=2.3.0->pandas_datareader)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from requests>=2.3.0->pandas_datareader)
Requirement already up-to-date: certifi>=2017.4.17 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from requests>=2.3.0->pandas_datareader)
Requirement already up-to-date: numpy>=1.9.0 in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas>=0.19.2->pandas_datareader)
Requirement already up-to-date: python-dateutil in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas>=0.19.2->pandas_datareader)
Requirement already up-to-date: pytz>=2011k in /Users/ferraz/anaconda2/lib/python2.7/site-packages (from pandas>=0.19.2->pandas_datareader)`

**Comment by bashtage** [comment]
Yahoo was broken when 0.6 was released.  Since 0.6 a patch using scraping has been merged into master.  If you want to use Yahoo then you will need to install from master.

**Comment by bashtage** [comment]
`pip install git+https://github.com/pydata/pandas-datareader`

**Comment by sudoFerraz** [comment]
Unfortunately that did not work

`>>> pandas_datareader.__version__
u'0.6.0+4.g0debb02'`

`>>> df = web.DataReader('BRL=X', 'yahoo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ferraz/anaconda2/lib/python2.7/site-packages/pandas_datareader/data.py", line 290, in DataReader
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Daily'))
pandas_datareader.exceptions.ImmediateDeprecationError:
Yahoo Daily has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues
`

**Comment by BrianDAllen** [comment]
As a temporary fix, here is a wrapper I put together that utilizes scraping yahoo finance to return a pandas DataFrame of historical stock prices or dividends.

https://github.com/BrianDAllen/pandas_yahoo_historical_stocks

**Comment by jasonhei1** [comment]
@BrianDAllen I have received an error message upon importing historical_prices_and_dividends. Would you advise what will be the possible problem? Thanks

TypeError                                 Traceback (most recent call last)
<ipython-input-8-c669b19ba389> in <module>()
      2 df_stocks = historical_prices_and_dividends.get_historical_prices(ticker="IBM",
      3                                                                  start_date=datetime.datetime(2017,1,1),
----> 4                                                                  end_date=datetime.datetime.now())
      5 
      6 df_stocks.head()

~\Desktop\Work\xuhu wan\mooc\Topic1WhatDataScientistsDo\historical_prices_and_dividends.py in get_historical_prices(ticker, start_date, end_date)
     33 
     34     # find the json object in the response, format it, and load it
---> 35     index_s = response.find("HistoricalPriceStore")
     36     index_e = response.find("isPending", index_s)
     37 

TypeError: a bytes-like object is required, not 'str'

**Comment by sudoFerraz** [comment]
@BrianDAllen 
`>>> df_stocks = historical_prices_and_dividends.get_historical_prices(ticker="BRL=X", start_date=datetime.datetime(2017,1,1), end_date=datetime.datetime.now())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "historical_prices_and_dividends.py", line 41, in get_historical_prices
    mm = json.loads(json_string)
  File "/Users/ferraz/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/ferraz/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ferraz/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by jingsupo** [comment]
I get data by this way:
![baba](https://user-images.githubusercontent.com/7351235/37620700-f1857a74-2bf7-11e8-844e-4d0cee1efa8f.png)

**Comment by jaycode** [comment]
Hi there, some updates to empyrical module should fix this issue. See my fix commit above.

**Comment by prayank66** [comment]
I tried with below code in Python 3: 

>>> import pandas_datareader as pdr
>>> import datetime
>>> start = datetime.datetime(2018,1,1)
>>> end = datetime.date.today()
>>> baba = pdr.get_data_yahoo('BABA',start,end)

Still getting this error: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by JeremieGauthier** [comment]
```
from pandas_datareader import data as pdr
import plotly.offline as py_offline
import plotly.graph_objs as go
import fix_yahoo_finance as yf

py_offline.init_notebook_mode(connected=True)

yf.pdr_override()
mcd = pdr.get_data_yahoo("MCD", start="2005-07-01", end="2005-07-31")
mcd_candle = go.Candlestick(x=mcd.index,
                            open=mcd.Open,
                            high=mcd.High,
                            low=mcd.Low,
                            close=mcd.Close,
                            increasing=dict(line=dict(color= '#00FF00')),
                            decreasing=dict(line=dict(color= '#FF0000'))
                           )
data = [mcd_candle]

layout = go.Layout(
    plot_bgcolor='rgb(59,68,75)'
)

fig = go.Figure(data=data, layout=layout)
```

That code worked fine for me with `yf.pdr_override()`

**Comment by rkohli3** [comment]
Could we have options Data too?

**Comment by boromirmonk** [comment]
I'm having this issue. Do you have any recommendations on how I can do it differently?

**Comment by gyfeather** [comment]
Thanks a lot.when i try to use Python 3,then:
 File "pandas\_libs\index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Data'
what is wrong with this?

**Comment by wza47** [comment]
Had the same issue as you gyfeather. Fixed it with 2 lines of code. Add the below lines and your script should work. 

import fix_yahoo_finance as yf
yf.pdr_override()

Make sure you have pip installed fix_yahoo_finance already.

**Comment by ashokjha** [comment]
same error.

**Comment by maldonadoeconomist** [comment]
Hello, I see the last post was written 2 years ago. I face the same problem.
Is there any solutions so far? I'm sorry I am new in this.

from pandas_datareader.data import Options
fb_options=Options('FB','yahoo')

---------------------------------------------------------------------------
ImmediateDeprecationError                 Traceback (most recent call last)
<ipython-input-21-e5289e5c45cd> in <module>
      1 from pandas_datareader.data import Options
----> 2 fb_options=Options('FB','yahoo')

~\anaconda3\lib\site-packages\pandas_datareader\data.py in Options(symbol, data_source, session)
    690         data_source = "yahoo"
    691     if data_source == "yahoo":
--> 692         raise ImmediateDeprecationError(DEP_ERROR_MSG.format("Yahoo Options"))
    693         return YahooOptions(symbol, session=session)
    694     else:

ImmediateDeprecationError: 
Yahoo Options has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

**Comment by david2588e** [comment]
Hi ,
If you just want to download yahoo price information on stock, you can use the following:

from pandas_datareader import data as pdr

mcd = pdr.get_data_yahoo("MCD", start="2005-07-01", end="2005-07-31")

I checked in Python 3.6, it looks fine

mcd
Out[34]:
                 High        Low       Open      Close    Volume  Adj Close
Date
2005-06-30  28.200001  27.740000  28.049999  27.750000   8062100  17.538118
2005-07-01  28.129999  27.719999  27.809999  27.940001   4486700  17.658199
2005-07-05  28.090000  27.709999  27.820000  27.969999   4017200  17.677166
2005-07-06  27.990000  27.610001  27.969999  27.700001   4709800  17.506523



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: maldonadoeconomist<mailto:notifications@github.com>
发送时间: 2020年9月11日 1:05
收件人: pydata/pandas-datareader<mailto:pandas-datareader@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [pydata/pandas-datareader] ImmediateDeprecationError: Yahoo Actions has been immediately deprecated due to large breaks in the API without the introduction of a stable replacement. (#487)


Hello, I see the last post was written 2 years ago. I face the same problem.
Is there any solutions so far? I'm sorry I am new in this.

from pandas_datareader.data import Options
fb_options=Options('FB','yahoo')


ImmediateDeprecationError Traceback (most recent call last)
in
1 from pandas_datareader.data import Options
----> 2 fb_options=Options('FB','yahoo')

~\anaconda3\lib\site-packages\pandas_datareader\data.py in Options(symbol, data_source, session)
690 data_source = "yahoo"
691 if data_source == "yahoo":
--> 692 raise ImmediateDeprecationError(DEP_ERROR_MSG.format("Yahoo Options"))
693 return YahooOptions(symbol, session=session)
694 else:

ImmediateDeprecationError:
Yahoo Options has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

―

**Comment by phenomenal001** [comment]
This will work fine
1. Download CSV file of the data from yahoo which you want to use .
2.  import yfinance as yf
yf.pdr_override()
3. write the code you want and run the code

Make sure you have pip installed yfiance




Hope this Work

**Comment by Zanejins** [comment]
it is obvious that the api, get_data_yahoo, goes wrong.
Here is my solution:
  First, install fix_yahoo_finance: pip install fix_yahoo_finance --upgrade --no-cache-dir
  next, before you use the api, insert the code:
          import fix_yahoo_finance as yf
         yf.pdr_override()

Best wishes!
